language: node_js
node_js: node
services:
  mongodb
env:
  MONGODB_URI=mongodb://localhost:27017/notes
deploy:
  provider: heroku
  app:
    master: alchemy-notes
  api_key:
    secure: UER9w8EsJ+YbW6qULFVdDa86AVmyvigGOqIBZz7GGGKypN+6ZOuXXhIVjxAOG4UCaxfRM4bcdH2l8o5CeMEajHMV1gsI/BkIG/QZAhty+bLHoRqlzw7UtBivFjAOtp/4lIXOKKIWVgjZOcyupe2bWPdUmQ00+dnqHNK8MqlMcxogkRZUISihcgG6bStr2eMp5LiMcWR/qcUHyYSMUKMwJUgVB9Bg3Wc4qruhIoKDHEXMAuzw92/uwg9VWu///nXLsUeJqhodmmqk+JliqYxutIYNtBecyC9Zrg3qXLvsS9PHuCsOhUt5Sly0n5nROSTFV+B2xxXPZy8q2BuwmDGYqlFWNTFs66lGTr5ygtADJVsWISz60pR/It0/1oHHpymhDkxYzsmhwVQ38JkTes0SsVXcIJMHYzs1uRXN+n6xkwGjUIQY4FQnEe4zxhW7/Cg3KRgHng5qLAZBjT4j2JrY5oUGCGHvJc/yLr+4r8r1TXQnAXEHFr+93zLeMmfOdO+CUNTzGnJHr/UApV4jqdXXWYBOc7236xVujM/4CrEtO5tpdks1VblQpyE9icfnYZnQoaiL1aHDxhK03BM0/HwfmGyF6YscO6XJGaju6KEOgcmI6zYtcyknlUQVMUIqhrBatt6aJ/PG8/lOfrET695+HA4QmSE48QS+O8PhwxBg1CI=
